project:
  type: website
  output-dir: docs

website:
  description: "Plataforma institucional de gestão agrícola em produção de cucurbitáceas e rastreabilidade técnica baseada em dados."
  site-url: "https://marlenildo.github.io/melonmundi-site-publico"
  favicon: assets/img/favicon.png
  search: false
  page-navigation: true

  navbar:
    pinned: true
    collapse: true
    # collapse-below: lg
    background: none
    foreground: "#548238"
    logo: "assets/img/nova_logomm.png"
    logo-alt: "MelonMundi - Global Solutions logo."
    toggle-position: right
    left:
      - text: "Página Inicial"
        href: index.qmd
      - text: "Quem Somos"
        href: about.qmd
    right:
      - text: "Entrar"
        href: https://acervo.melonmundi.local/login
        icon: box-arrow-in-right

  page-footer:
    right: "&copy; 2026 MelonMundi - Global Solutions"
    left: "![](assets/img/nova_logomm.png){width=60px}"
    center:
      - text: "Página Inicial"
        href: index.qmd
      - text: "Quem Somos"
        href: about.qmd
      - text: "Privacidade"
        href: privacy.qmd
      - text: "Termos de Uso"
        href: terms.qmd

format:
  html:
    lang: pt-BR
    css: assets/css/styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

    # SEO & social sharing
    open-graph: true
    twitter-card: true

    # Usabilidade (opcional, já validado)
    reader-mode: true
    page-navigation: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

