project:
  type: website
  output-dir: docs
lang: pt-BR

website:
  description: "Plataforma institucional de gestão agrícola em produção de cucurbitáceas e rastreabilidade técnica baseada em dados."
  site-url: "https://marlenildo.github.io/melonmundi-site-publico"
  favicon: assets/img/favicon.png
  search: false
  page-navigation: true
  cookie-consent:
    type: express
    style: headline
    language: pt
    title: "Cookies e privacidade"
    description: "Este site utiliza cookies essenciais para garantir o funcionamento adequado e melhorar a sua experiência de navegação."
    accept-label: "Aceitar"
    decline-label: "Recusar"
    learn-more-label: "Saiba mais"
    learn-more-url: "/privacy.html"
   

  navbar:
    pinned: true
    collapse: true
    collapse-below: lg
    background: none
    foreground: "#548238"
    logo: "assets/img/nova_logomm.png"
    logo-alt: "MelonMundi - Global Solutions logo."
    toggle-position: right
    left:
      - text: "Página Inicial"
        href: index.qmd
      - text: "Quem Somos"
        href: sobre-nos.qmd
      - text: "Mais"
        menu:
          - text: "Política de Privacidade"
            href: politica-de-privacidade.qmd
          - text: "Termos de Uso"
            href: termos-de-uso.qmd
    right:
      - text: "Entrar"
        # href: acervo.qmd
        # href: http://acervo.melonmundi.local:8000/oauth2/start
        href: https://acervo.marlenildo.site
        icon: box-arrow-in-right

  page-footer:
    right: "Copyright &copy; 2026 MelonMundi - Global Solutions"
    left: "![](assets/img/nova_logomm.png){width=80px}"
    center:
      - text: "Página Inicial"
        href: /index.html
      - text: "Quem Somos"
        href: /sobre-nos.html
      - text: "Privacidade"
        href: /politica-de-privacidade.html
      - text: "Termos de Uso"
        href: /termos-de-uso.html

format:
  html:
    lang: pt-BR
    css: assets/css/styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

    # SEO & social sharing
    open-graph: true
    twitter-card: true

    # Usabilidade (opcional, já validado)
    reader-mode: true
    page-navigation: true
    include-after-body:
      - text: |
          <script src="assets/js/scroll-reveal.js"></script>
      - text: |
          <script src="assets/js/home-navbar-scroll.js"></script>
      - text: |
          <script src="assets/js/home-carousel.js"></script>
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

